name: savingsbox_test
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: "none"

# The following defines the version and build number for your application.
version: 1.0.0+1

# The following line ensures that the package versions are locked to the versions
environment:
  sdk: ">=3.4.4 <4.0.0"

# Add dependencies here
dependencies:
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.2.0
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_gen: ^5.7.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.4
  internet_connection_checker: ^2.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.4.0
  lottie: ^3.1.2
  page_transition: ^2.1.0
  shimmer: ^3.0.0
  toastification: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/
    - .env

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path_ios: "assets/images/app_ios_icon.png"
#   image_path_android: "assets/images/app_android_icon.png"
#   adaptive_icon_background: "#000000"
#   adaptive_icon_foreground: "assets/images/app_android_icon.png"
# flutter_native_splash:
#   android: true
#   ios: true
#   color: "#4E5079"
#   image: assets/images/app_icon.png
#   android_12:
#     image: assets/images/app_icon.png
